<a href="https://colab.research.google.com/github/gaurav3829/python_libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#check version
np.__version__



'2.1.3'

In [ ]:
#array(),function()
a=np.array([1,2,3])
print(type(a))
print(a)



<class 'numpy.ndarray'>
[1 2 3]


In [ ]:
#dimention of array
a=[3,4,5,6]
a1=np.array(a)
print(a1)
print(a1.ndim)
a1=[[3,4,5,6],[4,5,6,7]]
a2=np.array(a1)
print(a2)

a2.ndim



[3 4 5 6]
1
[[3 4 5 6]
 [4 5 6 7]]


2

In [ ]:
a1=[3,4,5,6]
a2=np.array(a1)
print(type(a1))
print(type(a2))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
a=[3,4,5,5]
a1=np.array(a)
a1.shape

(4,)

In [ ]:
a=[[[3,4,5]],[[2,3,4]],[[6,7,8]]]
a1=np.array(a)
a1.reshape(3,3)

array([[3, 4, 5],
       [2, 3, 4],
       [6, 7, 8]])

In [ ]:
x=np.array([[1,2,3],[4,5,6]])
x1=x.flatten(order="c")
print(x1)

[1 2 3 4 5 6]


In [ ]:
#asarray()--we want convert from one data type to another data type
#new_var=np.asarray(array,dtype=datatype)

x=[1,2,3,4]
x1=np.asarray(x,dtype=float)#float datatypr convert
print(x1)

[1. 2. 3. 4.]


In [ ]:
x1=np.asarray(x,dtype=str)#string data type convrtion
print(x1)

['1' '2' '3' '4']


In [ ]:
x1=np.asarray(x,dtype=complex)
print(x1)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [ ]:
#arange()
#it is an inbuilt method which is used to the sequence of int
#between the specified limit

#syntax:--->np.arange(si,ei+1,stepvalue)


x=np.arange(1,11,1)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#linspace
#It is an inbuilt method which is used to create the equally
#space values between the given limits


#syntax:--> np.linspace(si,ei,num,retstep=true)

x=np.linspace(1,10,5,retstep=True)
print(x)

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), np.float64(2.25))


In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3,4,5,6,7,8,9])

print(x.ndim)

1


In [4]:
print(x.shape)

(9,)


In [5]:
x=np.array([[1,2,3,4],[5,6,7,8]])

print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
print(x.reshape(-1))

[1 2 3 4 5 6 7 8]


In [9]:
print(x.flatten())

[1 2 3 4 5 6 7 8]


In [12]:
print(x.flatten(order="C"))
y=x.flatten(order="F")
print(y)

[1 2 3 4 5 6 7 8]
[1 5 2 6 3 7 4 8]


In [ ]:
#asarray is convert data type

In [15]:
x=np.asarray([1,2,3],dtype=float)
print(x)

print(type(x))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [17]:
x=np.arange(0,20,2)
print(x)

[ 0  2  4  6  8 10 12 14 16 18]


In [20]:
np.linspace(1,2,6,retstep=False)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [25]:
y=np.random.randn(2,4,3)
print(y)

[[[ 0.39270001 -1.55357675  0.37813049]
  [-1.46334616 -1.27303167 -1.05074868]
  [ 1.41421292 -0.39590281  1.66663549]
  [-1.35761732 -0.28289283 -0.16413339]]

 [[-0.91572825  1.2249366   0.51530539]
  [-0.40003349  1.12960162  0.25160797]
  [ 1.4115077  -1.1376437   0.18399187]
  [-1.20009162 -0.67535909  0.17315677]]]


In [29]:
s=np.array([1,3,4,])
s1=s.copy()
print(s)
print(s1)


[1 3 4]
[1 3 4]


In [31]:
x=np.array([1,2,3,1,3,4,5,8,91,1])
y=np.where(x==10)
print(y)

(array([], dtype=int64),)


In [32]:
y=np.array_split(x,10)
print(y)

[array([1]), array([2]), array([3]), array([1]), array([3]), array([4]), array([5]), array([8]), array([91]), array([1])]


In [33]:
print(x)

[ 1  2  3  1  3  4  5  8 91  1]


In [34]:
c=np.append(x,34)
print(c)

[ 1  2  3  1  3  4  5  8 91  1 34]


In [35]:
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [38]:
c=np.append(b,[100,"hiii",5])
print(c)

['1' '2' '3' '4' '100' 'hiii' '5']


In [43]:
s=np.insert(b,2,[23,45,6])
print(s)

[ 1  2 23 45  6  3  4]


In [44]:
print(s)

[ 1  2 23 45  6  3  4]


In [48]:
d=np.delete(s,3)
d

array([ 1,  2, 23,  6,  3,  4])