<a href="https://colab.research.google.com/github/gaurav3829/python_libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#check version
np.__version__



'2.1.3'

In [ ]:
#array(),function()
a=np.array([1,2,3])
print(type(a))
print(a)



<class 'numpy.ndarray'>
[1 2 3]


In [ ]:
#dimention of array
a=[3,4,5,6]
a1=np.array(a)
print(a1)
print(a1.ndim)
a1=[[3,4,5,6],[4,5,6,7]]
a2=np.array(a1)
print(a2)

a2.ndim



[3 4 5 6]
1
[[3 4 5 6]
 [4 5 6 7]]


2

In [ ]:
a1=[3,4,5,6]
a2=np.array(a1)
print(type(a1))
print(type(a2))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
a=[3,4,5,5]
a1=np.array(a)
a1.shape

(4,)

In [ ]:
a=[[[3,4,5]],[[2,3,4]],[[6,7,8]]]
a1=np.array(a)
a1.reshape(3,3)

array([[3, 4, 5],
       [2, 3, 4],
       [6, 7, 8]])

In [ ]:
x=np.array([[1,2,3],[4,5,6]])
x1=x.flatten(order="c")
print(x1)

[1 2 3 4 5 6]


In [ ]:
#asarray()--we want convert from one data type to another data type
#new_var=np.asarray(array,dtype=datatype)

x=[1,2,3,4]
x1=np.asarray(x,dtype=float)#float datatypr convert
print(x1)

[1. 2. 3. 4.]


In [ ]:
x1=np.asarray(x,dtype=str)#string data type convrtion
print(x1)

['1' '2' '3' '4']


In [ ]:
x1=np.asarray(x,dtype=complex)
print(x1)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [ ]:
#arange()
#it is an inbuilt method which is used to the sequence of int
#between the specified limit

#syntax:--->np.arange(si,ei+1,stepvalue)


x=np.arange(1,11,1)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#linspace
#It is an inbuilt method which is used to create the equally
#space values between the given limits


#syntax:--> np.linspace(si,ei,num,retstep=true)

x=np.linspace(1,10,5,retstep=True)
print(x)

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), np.float64(2.25))
